language: php

branches:
- master

php:
  - 5.6

before_install:
  - pecl install channel://pecl.php.net/pthreads-2.0.7
  - pecl install channel://pecl.php.net/weakref-0.2.4
  - echo | pecl install channel://pecl.php.net/yaml-1.1.1

before_script:
  - git clone --recursive https://github.com/PocketMine/PocketMine-MP.git PocketMine
  - mkdir PocketMine/plugins
  - wget -O ConsoleScript.php https://raw.githubusercontent.com/PocketMine/DevTools/master/src/DevTools/ConsoleScript.php
  - php ConsoleScript.php -dphar.readonly=0 --make StatsCore --out PocketMine/plugins/StatsCore.phar
  - php ConsoleScript.php -dphar.readonly=0 --make AutoKiller --out PocketMine/plugins/AutoKiller.phar
  - cd PocketMine
  - wget -O server.properties https://gist.githubusercontent.com/PEMapModder/6ac745b5ff0283c8c02f/raw/statscore-server.properties
  - wget -O pocketmine.yml https://gist.githubusercontent.com/PEMapModder/6ac745b5ff0283c8c02f/raw/statscore-pocketmine.yml

script:
  - php tests/TravisTest.php

after_success:
  - wget -O upload.php https://gist.githubusercontent.com/PEMapModder/6ac745b5ff0283c8c02f/raw/upload.php
  - php upload.php --file plugins/StatsCore.phar --target http://example.com/statscore_upload.php --commit $TRAVIS_COMMIT --branch $TRAVIS_BRANCH --pr $TRAVIS_PULL_REQUEST
