language: php

branches:
- master

php:
- 5.6

before_script:
  - mkdir plugin-test
  - cd plugin-test
  - wget -O PocketMine.phar https://github.com/PocketMine/PocketMine-MP/releases/download/Alpha_1.4dev-491/PocketMine-MP_Alpha_1.4dev-491.phar
  - pecl install channel://pecl.php.net/pthreads-2.0.7
  - pecl install channel://pecl.php.net/weakref-0.2.4
  - echo | pecl install channel://pecl.php.net/yaml-1.1.1
  - mkdir plugins
  - wget -O ConsoleScript.php https://github.com/PocketMine/DevTools/blob/master/src/DevTools/ConsoleScript.php
  - echo > server.properties
  - php ConsoleScript.php -dphar.readonly=0 --make ../$TRAVIS_BUILD_DIR --out plugins/StatsCore.phar
  - wget -O server.properties https://gist.githubusercontent.com/PEMapModder/6ac745b5ff0283c8c02f/raw/ae7e581ee8a22636b160dafe99cb8e02f3e210b0/statscore-server.properties

script:
  - php PocketMine.phar
