---
log database:
  # types available: json, sqlite3, mysql, yaml
  type: yaml
  json:
    # add unnecessary spaces and newlines to the files so that the fies look prettier
    pretty print: true
    dir: players
  yaml:
    dir: players
  sqlite3:
    file: logs.sq3
  mysql:
    global: true
    # global: a MySQL database that all plugins can access.
    # If other plugins use this, server performance with MySQL could be improved.
    # If you set this to true, the following five lines about connection details will be ignored and a global mysql database will be constructed (if not already constructed).
    host: example.com
    username: "Anonymous"
    password: "123456AintGoodPassword"
    database: "statscore"
    port: 3306
global mysql database: # a connection is built with this if any plugins (including this one) want to use the global database. Only one connection will be constructed.
  host: example.com
  username: "Anonymous"
  password: "123456AintGoodPassword"
  database: "statscore"
  port: 3306
...
